lchavarria0D30/TimeMgt_Group4_SWENG894

- BACKEND/userAuth/src/main/java/com/apptime/auth/config/SecurityConfig.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskCategoryController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskCategory.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/to/Category.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskCategoryRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskCategoryService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskCategoryServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/JsonUtil.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskCategoryControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/UserControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskCategoryServiceTest.java
- Unit_Test/Sprint1_Unit_Test.txt
[TMGP4-134] Create Backend Code
https://sweng894group4.atlassian.net/browse/TMGP4-134
[TMGP4-132] Create Backend Code
https://sweng894group4.atlassian.net/browse/TMGP4-132
Anyone could please review this PR? If no objections I will merge it on the Sunday. Thanks.
> Implementation of private/public categories

- BACKEND/userAuth/pom.xml
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskCategoryControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskCategoryServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-134
Fix the unit test issue
> [TMGP4-134] Create Backend Code

- BACKEND/userAuth/src/main/java/com/apptime/auth/model/Task.java
> update to task model

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskCategoryController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskCategory.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskCategoryRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskCategoryService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskCategoryServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskCategoryControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskCategoryServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-132
Fix issue caused by new authorization mechanism (OAuth, no new users after signup/login)
> [TMGP4-132] Create Backend Code

- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/JsonUtil.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskCategoryControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskManagerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskCategoryServiceTest.java
[TMGP4-170] Analysis backend class: TaskCategoryServiceTest
https://sweng894group4.atlassian.net/browse/TMGP4-170
[TMGP4-169] Analysis backend class: TaskManagerTest
https://sweng894group4.atlassian.net/browse/TMGP4-169
[TMGP4-168] Analysis backend class: TaskCategoryControllerTest
https://sweng894group4.atlassian.net/browse/TMGP4-168
[TMGP4-167] Analysis backend class: JsonUnit
https://sweng894group4.atlassian.net/browse/TMGP4-167
> Fix warnings in backend unit test classes (found by Idea Analyze)

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskCategoryController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskCategoryRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskCategoryService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskCategoryServiceImpl.java
https://sweng894group4.atlassian.net/browse/TMGP4-172
Including two Jira tickets:
[TMGP4-165] Analysis backend class: TaskCategoryServiceImpl
https://sweng894group4.atlassian.net/browse/TMGP4-165
[TMGP4-166] Analysis backend class: TaskCategoryController
https://sweng894group4.atlassian.net/browse/TMGP4-166
> [TMGP4-172] Qi's Code from Sprint 1

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/AbstractionAuthenticationController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/NotificationController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskCategoryController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/filter/UserFilter.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/Notification.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/NotificationRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/NotificationService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskManagerService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/NotificationServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/NotificationControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/NotificationServiceTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskManagerServiceTest.java
Provide the API to retrieve new notifications, snooze notifications, delete notifications
The system would be able to create notifications to remind user one task is starting
> [TMGP4-199] Create Backend Code

- BACKEND/userAuth/src/main/java/com/apptime/auth/service/NotificationService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/NotificationServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/NotificationControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/NotificationServiceTest.java
Create notifications for exceeded tasks
> [TMGP4-202] Create Backend Code

- BACKEND/userAuth/src/main/java/com/apptime/auth/config/TaskStateMachine.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskManager.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskManagerService.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskManagerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskStateMachineTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskManagerServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-270
https://sweng894group4.atlassian.net/browse/TMGP4-271
https://sweng894group4.atlassian.net/browse/TMGP4-263
> Create Backend Unit Tests for start/pause/complete tasks

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskReportController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskReport.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskReportType.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskReportRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/NotificationService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskManagerService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskReportService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/NotificationServiceImpl.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskReportServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskManagerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskReportControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskManagerServiceTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskReportServiceImplTest.java
[TMGP4-211] Create Backend Code
https://sweng894group4.atlassian.net/browse/TMGP4-211
[TMGP4-208] Create Backend Code
https://sweng894group4.atlassian.net/browse/TMGP4-208
For two use cases:
[TMGP4-31] Report on Tasks Completed Behind Schedule
[TMGP4-26] Report on Tasks Completed Ahead of Schedule
When one task is done, the system would generate one report for the task, and send one notification to the user.
The Report would contain if the task is done
1. ON_TIME: the actual end time is in 10 minutes of the scheduled end time
2. EARLIER: the actual end time is more than 10 minutes earlier than the scheduled end time
3. LATER: the actual end time is more than 10 minutes later than the scheduled end time
And the difference between the actual end time and the scheduled end time
The …
> Generate report for task once it is done

- Unit_Test/app.component.spec.ts
- Unit_Test/create-task-dialog.component.spec.ts
- Unit_Test/delete-task-dialog.component.spec.ts
- Unit_Test/edit-task-dialog.component.spec.ts
- Unit_Test/task-category.component.spec.ts
- Unit_Test/tasks.component.spec.ts
The files associated within this folder contains the most up to unit test. The edit-task-dialog.spec.ts file contains a defect within the ts file and may be resolved once the new pull request from the development team has been accomplished.
> Frontend Unit Test Files 22March2020 - ChavarriaL

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskReportController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskReport.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskReportRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskManagerService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskReportService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/NotificationServiceImpl.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskReportServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskReportControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskReportServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-211
[TMGP4-208] Create Backend Code
https://sweng894group4.atlassian.net/browse/TMGP4-208
Fix issues in the PR review
> [TMGP4-211] Create Backend Code

- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications-service.service.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications/notifications.component.ts
Added Notification,Snooze and Cancel features
> Notification, Snooze and Cancel features are added

- FRONTEND/newFrontEnd/apTime/package-lock.json
- FRONTEND/newFrontEnd/apTime/package.json
- FRONTEND/newFrontEnd/apTime/src/app/app.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications/notifications.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/tasks/tasks.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/tasks/tasks.component.ts
[TMGP4-137] Create Frontend Code - https://sweng894group4.atlassian.net/browse/TMGP4-137
Ran the npm audit and there were changes made into the package-lock.json
> Added View tasks by specific date code

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskManager.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskManagerTest.java
I fixed the majority issues. But for the test case `testShowAddedSince` (and associated business logic), I have no idea what is the correct behavior. So @bashiir could you please take a look and fix it? Thanks.
> Fix the unit test issue

- FRONTEND/newFrontEnd/apTime/package-lock.json
- FRONTEND/newFrontEnd/apTime/package.json
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.ts
- README.md
Vulnerabilities fix (package.json)
Added the dropdown for categories in the edit task dialog
> Vulnerabilities fix [TMGP4-282] and Workaround for [TMGP4-281]

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskReportController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/to/Report.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskReportRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskReportService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskReportServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskReportControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/model/to/ReportTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskReportServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-208
Update the API to accept startDate and endDate
Fix the duration format in the response
> [TMGP4-208] Create Backend Code

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskManager.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/Task.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskCategory.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskCategoryRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskManagerService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskCategoryServiceImpl.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskReportServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskManagerServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-284
The task would have multiple categories
Fix a bug
> [TMGP4-284]: [Backend] The system should be able to connect task with categories

- FRONTEND/newFrontEnd/apTime/src/app/app.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/auth/auth.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/confirm-task-dialog/confirm-task-dialog.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/delete-task-dialog/delete-task-dialog.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/home/home.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications-service.service.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications/notifications.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/start-task-dialog/start-task-dialog.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/task-category/task-category.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/tasks/tasks.component.spec.ts
Unit test updates have been completed for Sprint 2. The Official Run has been completed for Frontend Unit Test.
> Unit Test Update Sprint 2 Offical Run

- FRONTEND/newFrontEnd/apTime/src/app/components/report/report.component.spec.ts
Sprint 2 Official Test Run - Unit Test file update. New Branch was just created to upload this file as my branch does not contain the Report folder. Once all commits have been made I will mirror it to my branch. 
Thanks,
> report.component.spec - Updated Unit Test SPT2

- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/tasks/tasks.component.ts
> Bug Fix: Create/Edit Task (Time) and added sorted tasks in the Tasks view

- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskReportServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskReportServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-300
Bug fixing
> [TMGP4-300] Actual Duration not working correctly in Completed Tasks Report

- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskReport.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/to/Report.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskReportServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/model/to/ReportTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-306
Add the date and time in the report
> [TMGP4-306]: [Backend] Start Date and End Date need to be added to Complete Tasks Report

- BACKEND/userAuth/src/main/java/com/apptime/auth/model/to/Report.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/NotificationService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/NotificationServiceImpl.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/util/DurationUtil.java
https://sweng894group4.atlassian.net/browse/TMGP4-299
Fix the duration format issue
> [TMGP4-299] Notifications should show duration in better format

- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/home/home.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/tasks/tasks.component.ts
BUG-347 [https://sweng894group4.atlassian.net/browse/TMGP4-347]
BUG-346 [https://sweng894group4.atlassian.net/browse/TMGP4-346]
> Date fix and sort issue

- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications/notifications.component.spec.ts
- Unit_Test/notifications.component.spec.ts
This file was forgotten but is not being requested.
> Added Notification.Component.spect.tS

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskCategoryController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/model/TaskCategory.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskCategoryRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskCategoryService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskCategoryServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskCategoryControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskCategoryServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-362
Provide a new API to retrieve all accessible categories
> [TMGP4-362] Backend changes

- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.css
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.ts
Front-end changes (Categories for a user) TMGP4-361 [https://sweng894group4.atlassian.net/browse/TMGP4-361]
> Categories [Bug Fix]

- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/TaskCategoryRepository.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskCategoryServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-370
Sort the category list by alphabetical order
> [TMGP4-370] Sort Categories Alphabetically

- FRONTEND/newFrontEnd/apTime/src/app/components/confirm-task-dialog/create-task-dialog.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications-service.service.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/notification/notifications/notifications.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/start-task-dialog/start-task-dialog.component.spec.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/tasks/tasks.component.spec.ts
I have updated 7 Unit Test files, please review.
> Frontend Unit Test Updates - 10 April 2020

- FRONTEND/newFrontEnd/apTime/src/app/components/report/report.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/report/report.component.ts
Please Review: Updated Report and completed JIRA number :https://sweng894group4.atlassian.net/browse/TMGP4-206 and https://sweng894group4.atlassian.net/browse/TMGP4-207
> Updated Report to reflect latest discussion related to TMPG4 206 and 207

- FRONTEND/newFrontEnd/apTime/src/app/components/report/report.component.html
> fixed report html file issue

- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskManager.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/controller/TaskSummaryController.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/repository/AllUserTaskSummaryRepository.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskSummaryService.java
- BACKEND/userAuth/src/main/java/com/apptime/auth/service/impl/TaskSummaryServiceImpl.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/controller/TaskSummaryControllerTest.java
- BACKEND/userAuth/src/test/java/com/apptime/auth/service/TaskSummaryServiceTest.java
https://sweng894group4.atlassian.net/browse/TMGP4-332
https://sweng894group4.atlassian.net/browse/TMGP4-334
Update APIs /summary/mine
> Implement TMPG4-332, TMPG4-334

- FRONTEND/newFrontEnd/apTime/src/app/components/auth/auth.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.css
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/dashboard/dashboard.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.css
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.css
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/tasks/tasks.component.ts
> Suggestions Added to Edit/Create/PopUp

- FRONTEND/newFrontEnd/apTime/src/app/components/task-category/task-category.component.css
- FRONTEND/newFrontEnd/apTime/src/app/components/task-category/task-category.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/task-category/task-category.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/services/category.service.ts
> Added Statistics to category

- BACKEND/userAuth/pom.xml
- BACKEND/userAuth/src/main/resources/application.yml
https://sweng894group4.atlassian.net/browse/TMGP4-380
To build project locally: mvn install
To build project to be deployed in AWS: mvn install -Denv=aws -DskipTests
> Backend changes for deploying to AWS

- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.css
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/create-task-dialog/create-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/edit-task-dialog/edit-task-dialog.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/start-popup-task/start-popup-task.component.ts
- FRONTEND/newFrontEnd/apTime/src/app/components/task-category/task-category.component.html
- FRONTEND/newFrontEnd/apTime/src/app/components/task-category/task-category.component.ts
1)	Address Categories issue sent in Scott’s email last night (may require Qi help for backend)
2)	Complete frontend Suggestion update (TMGP4-331/339)
3)	Complete frontend Statistics update (TMGP4-333/335)
> Suggestions and Statistics update, Bug Fixes (categories)

- BACKEND/userAuth/src/main/java/com/apptime/auth/service/TaskManagerService.java
- BACKEND/userAuth/src/main/resources/application.properties
refactored url for  python deployment on AWS
> refactored url for  python deployment on AWS

- FRONTEND/newFrontEnd/apTime/angular.json
> Fix for the prod buil error

- BACKEND/userAuth/src/main/resources/application.yml
@bashiir @scottweiss-pennstate Please review this PR. Thanks.
> Fix the python app's url for AWS
